ALTER TABLE receipts ADD COLUMN enrichment_status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE receipts ADD COLUMN ocr_confidence REAL;
ALTER TABLE receipts ADD COLUMN raw_ocr_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE receipts ADD COLUMN gst_status TEXT NOT NULL DEFAULT 'NOT_CHECKED';
ALTER TABLE receipts ADD COLUMN enrichment_version INTEGER NOT NULL DEFAULT 0;
