#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMAND="${1:-help}"; ENVIRONMENT="${2:-staging}"
fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
require() { command -v "$1" >/dev/null || fail "Required command not found: $1"; }
require_clean() { test -z "$(git -C "$ROOT" status --porcelain)" || fail "Git working tree must be clean."; }
project_var() { local name="GCP_${ENVIRONMENT^^}_PROJECT_ID"; printf '%s' "${!name:-}"; }
preflight() { for command in gcloud firebase terraform docker jq npm python3; do require "$command"; done; test "${AWS_DEPLOYMENT_FROZEN:-true}" = "true" || fail "AWS_DEPLOYMENT_FROZEN must remain true."; test "${PILOT_DEPLOY_ENABLED:-false}" = "false" || fail "PILOT_DEPLOY_ENABLED must remain false."; gcloud auth list --filter=status:ACTIVE --format='value(account)' | grep -q . || fail "Run: gcloud auth login"; printf 'GCP preflight passed. AWS remains frozen.\n'; }
plan() { preflight; local project; project="$(project_var)"; test -n "$project" || fail "Set GCP_${ENVIRONMENT^^}_PROJECT_ID."; local vars="${GCP_TFVARS_FILE:-}"; test -f "$vars" || fail "Set GCP_TFVARS_FILE to a private .tfvars file."; terraform -chdir="$ROOT/infra/gcp" init -backend=false; terraform -chdir="$ROOT/infra/gcp" validate; terraform -chdir="$ROOT/infra/gcp" plan -var-file="$vars" -out="/tmp/challanse-${ENVIRONMENT}.tfplan"; printf 'Speculative plan created at /tmp/challanse-%s.tfplan. Nothing was applied.\n' "$ENVIRONMENT"; }
build_image() { require_clean; preflight; local project image; project="$(project_var)"; test -n "$project" || fail "Set GCP_${ENVIRONMENT^^}_PROJECT_ID."; image="asia-south1-docker.pkg.dev/${project}/challanse/api:$(git -C "$ROOT" rev-parse HEAD)"; gcloud builds submit "$ROOT/services/gcp-api" --project "$project" --tag "$image"; gcloud artifacts docker images describe "$image" --project "$project" --format='value(image_summary.digest)'; }
deploy() { require_clean; preflight; local sha phrase; sha="$(git -C "$ROOT" rev-parse HEAD)"; read -r -p "Type DEPLOY ${ENVIRONMENT} ${sha}: " phrase; test "$phrase" = "DEPLOY ${ENVIRONMENT} ${sha}" || fail "Confirmation did not match."; local vars="${GCP_TFVARS_FILE:-}"; test -f "$vars" || fail "Set GCP_TFVARS_FILE."; terraform -chdir="$ROOT/infra/gcp" init; terraform -chdir="$ROOT/infra/gcp" apply -var-file="$vars"; npm --prefix "$ROOT" run build --workspace @challanse/client; firebase use "$ENVIRONMENT" --project "$(project_var)"; firebase deploy --only hosting,firestore:rules,storage --project "$(project_var)"; }
case "$COMMAND" in preflight) preflight;; plan) plan;; build-image) build_image;; deploy-staging) ENVIRONMENT=staging; deploy;; deploy-production) ENVIRONMENT=production; test "${GCP_PRODUCTION_APPROVED:-false}" = "true" || fail "Set GCP_PRODUCTION_APPROVED=true only after staging acceptance."; deploy;; *) printf '%s\n' "Usage: $0 {preflight|plan [staging|production]|build-image [staging|production]|deploy-staging|deploy-production}";; esac
