import { describe, expect, it } from 'vitest';
import { isValidReceiptId } from './receipt-id';

describe('receiptId validation (R2 key path-traversal guard)', () => {
  it('accepts the UUID v4 shape generated by the mobile app', () => {
    expect(isValidReceiptId('3f2c9a6e-4b1d-4f0e-9a8b-7c6d5e4f3a2b')).toBe(true);
    expect(isValidReceiptId('0A1B2C3D-4E5F-4A6B-8C9D-0E1F2A3B4C5D')).toBe(true); // case-insensitive
  });

  it('rejects path traversal and slash-separated values', () => {
    expect(isValidReceiptId('../../etc/passwd')).toBe(false);
    expect(isValidReceiptId('..%2F..%2Fsecret')).toBe(false);
    expect(isValidReceiptId('receipts/../../secret')).toBe(false);
    expect(isValidReceiptId('org/site/receipt')).toBe(false);
  });

  it('rejects non-UUID strings and malformed UUIDs', () => {
    expect(isValidReceiptId('a'.repeat(36))).toBe(false); // no dashes
    expect(isValidReceiptId('3f2c9a6e-4b1d-5f0e-9a8b-7c6d5e4f3a2b')).toBe(false); // version 5, not 4
    expect(isValidReceiptId('3f2c9a6e-4b1d-4f0e-9a8b-7c6d5e4f3a2')).toBe(false); // truncated
    expect(isValidReceiptId('')).toBe(false);
    expect(isValidReceiptId(undefined)).toBe(false);
    expect(isValidReceiptId(null)).toBe(false);
  });
});
